AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "bin/*"
    - "Gemfile.lock"
    - "vendor/bundle/**/*"

Rails:
  Enabled: true

# temporary - bug in 0.57.2
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
#  SupportedStyles: no_space
#  SupportedStylesForEmptyBrackets: no_space

Layout/IndentHash:
  EnforcedStyle: consistent
  IndentationWidth: 4

Layout/IndentArray:
  EnforcedStyle: consistent
  IndentationWidth: 4

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false # doesn't work properly with timestamptz

Rails/BulkChangeTable:
  Enabled: false
